### ISSUE TITLE
[Suggestion] Notifications tab support | currently this does not affect the notifications tab

### ISSUE THREAD

**Issue by CJStyles123** [wseagar/eight-dollars#21]
hope this is worked on in the future since currently it doesn't affect the notifications tab just the timeline/profile.

**Comment by Reprevise** [comment]
Yeah on the notifications tab for me it just shows the "Actually Verified" w/o their name.
![image](https://user-images.githubusercontent.com/25782944/201253902-ce06b53c-c48d-4f47-bf85-5dd42221aab5.png)

**Comment by wseagar** [comment]
I'm able to reproduce this one and I'll look at getting a fix into the next release 👍

**Comment by wseagar** [comment]
This bug was the cause of most of the weird issues people were reporting https://github.com/wseagar/eight-dollars/commit/a1d053706e70e7c62b06ffca040d52a6499d23ba

On master everything is now looking good. Changes will go out with v1.2 tomorrow. If there's any problems after that please feel feel to reopen this and thanks for reporting it!
