### ISSUE TITLE
Support for new types of checkmarks

### ISSUE THREAD

**Issue by firatciftci** [wseagar/eight-dollars#68]
Twitter has been rolling out its new checkmark system with businesses having a golden checkmark and governments having a grey one. [Here is a report on the new checkmarks](https://twitter.com/wongmjane/status/1600774456162816000), and [here is an example tweet with a golden checkmark](https://twitter.com/BBCWorld/status/1602339759812214784).

Could you add support to this new system? There could be some customization, in which the extension has a "classic" mode and all checkmarks appear blue. There could also be added functionality to change the icon of these new checkmarks and add custom labels next to them, similar to how it is done right now with the original vs. Blue checkmark configurations.

I have attached the colored checkmark specification image from the first linked tweet to here as well:
![FjcX0sEaAAAo3jM](https://user-images.githubusercontent.com/2052855/207169621-20cf309b-d44b-4897-9d4f-3c0a85be5895.jpeg) 
> Source: [@wongmjane](https://twitter.com/wongmjane)

**Comment by noway** [comment]
It kinda works without any changes. Government ones get augmented since the `isVerified` prop is set to `true`, business ones don't get augmented since `isVerified` prop is set to `false`.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2031472/211130288-bc0faed0-3f67-47a2-90d6-f745c12f88c1.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2031472/211130305-999fa353-4612-47d4-b424-27b3f13b4941.png">

We could probably make it better by augmenting business ones too, and doing more display types off of the `verifiedType` prop. Would be a cool feature.
