### ISSUE TITLE
Paid account not being flagged as paid [BUG]

### ISSUE THREAD

**Issue by david-rahrer** [wseagar/eight-dollars#81]
Chrome 108.0.5359.125 (Official Build) (64-bit)
Windows 10
Extension v 1.5
Twitter location: US

Twitter account:  https://twitter.com/JamesBradleyCA

I've run into a Twitter account (above) that does not display the paid indicator even though it is a paid account. I do see lots of paid accounts so it seems to be working properly otherwise. However, I have no idea how many other accounts this is happening with as I don't check them all. 

I thought you might want to see what is preventing this one from being flagged as it may not be the only one.

**Comment by mirzmaster** [comment]
I'm seeing the same for some accounts that are paid.  Here's another Twitter account which appears as Verified rather than Paid:  https://twitter.com/SahilBloom

I don't see any difference between this account's verification status message and another that gets labelled "Paid":

![image](https://user-images.githubusercontent.com/3869338/210830320-70f58193-e7f3-4c87-ad22-4cf8749d23d4.png)

![image](https://user-images.githubusercontent.com/3869338/210830563-42e16bcd-ae25-4379-a3c9-d7989b5b8865.png)

**Comment by noway** [comment]
It's because their accounts are both
```
isBlueVerified: true
```
and
```
isVerified: true
```

In other words, they had a real Verified badge before they bought Twitter Blue checkmark.

@david-rahrer 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2031472/211129425-183f9e6d-40e5-4df7-9e6a-9b669825005b.png">

@mirzmaster 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/2031472/211129415-3a9523bd-efe7-4ff2-aef5-c12f034c32d0.png">

This chrome extension gives legacy Verified status precedence over blue verified. So this is working as expected. We thought about giving those types of accounts a third status (legacy/blue verified hybrid) but it's technically challenging to do correctly in Twitter Spaces.

Closing as WONTFIX. Maybe we could revisit the "legacy/blue verified hybrid" status some time in the future as a separate feature though.
